### PR TITLE
FITStool cleanups: Issue 62/63/64 

### PR DESCRIPTION
**Pull request by o-smirnov**
Making Masks Easier Again

### CODE REVIEW

**Comment by bennahugo** [comment]
Sorry just saw this. The issue with the paste is, unless the WCS is exactly the same the projection rotation and sheering matricies aren't correctly applied. Is this the intent?

If you need this functionality I would recommend the dittering interpolation routines implemented in montage as an alternative @o-smirnov

**Comment by o-smirnov** [comment]
It's a simple tool for quick, dirty and simple stuff. I'm not going to bother with full WCS subtleties in fitstool. Montage is indeed the big guns, and does all of that, so why reinvent?

**Comment by bennahugo** [comment]
Ok but perhaps you should check whether the projection is the same in this case and raise an error if not?

**Comment by o-smirnov** [comment]
You know what, let me just print a big fat "use at own risk" warning, but no error. The WCS can never quite be the same (unless the central pixel exactly matches), but it can be close enough for government work. But let's leave it up to the [now educated] user to decide what close enough is.

**Comment by o-smirnov** [comment]
All right, added the warning, and another unrelated but badly needed feature.

**Review by bennahugo — APPROVED** [review]

**Pull request merged**
