### PR TITLE
Issue 51

### PR DESCRIPTION
**Pull request by SpheMakh**
- Tested and ready to go

### CODE REVIEW

**Comment by SpheMakh** [comment]
Getting this error when running test on python.36 . Does Timba have python support ?
```
2019/07/25 10:31:55 PYXIS: executing 'flag-ms.py /usr/local/lib/python3.6/dist-packages/Pyxis/recipies/meqtrees-batch-test/WSRT.MS -Y +L -f legacy -c':
Traceback (most recent call last):
  File "/usr/local/bin/flag-ms.py", line 285, in <module>
    import Owlcat.Flagger
  File "/usr/local/lib/python3.6/dist-packages/Owlcat/Flagger.py", line 3, in <module>
    import Timba.dmi
ModuleNotFoundError: No module named 'Timba'
2019/07/25 10:31:55 ABORT: flag-ms.py returned error code 1

```

**Comment by o-smirnov** [comment]
No, Timba hasn't been py3'ed quite yet. I guess we need to lock flag-ms.py to use py2 to avoid this problem for now?

**Comment by SpheMakh** [comment]
ok, disabling the python 3 test.

**Comment by gijzelaerr** [comment]
2 steps forward one back

**Comment by SpheMakh** [comment]
Actually, no need to disable it. It is already allowed to fail

**Comment by o-smirnov** [comment]
BTW @SpheMakh, now that this is merged, note that I've added a ``--copy-legacy`` option, which is basically a more straightforward (and easier on the eye) way to copy the FLAG column into a new flagset.

``flag-ms.py --copy-legacy FLAGSET --create foo.ms``

**Comment by o-smirnov** [comment]
Actually forget I said that for now, the new option can be broken. Don't change anything until my next PR goes in.

**Pull request merged**
